from routerts.config import CATCH22_NAMES, CANDIDATE_MODEL_SET_20

CANDIDATE_MODELS = CANDIDATE_MODEL_SET_20

CATCH22_CATEGORIES = {
    0: 'Distribution', 1: 'Distribution',
    2: 'Autocorrelation', 3: 'Autocorrelation',
    4: 'Autocorrelation',
    5: 'Fluctuation',
    6: 'Predictability',
    7: 'Stationarity', 8: 'Stationarity',
    9: 'Periodicity', 10: 'Periodicity',
    11: 'Autocorrelation',
    12: 'Predictability',
    13: 'Distribution', 14: 'Distribution',
    15: 'Periodicity',
    16: 'Stationarity', 17: 'Stationarity',
    18: 'Fluctuation', 19: 'Fluctuation',
    20: 'Periodicity',
    21: 'Predictability',
}

CATCH22_DESCRIPTIONS = {
    0: 'Mode of 5-bin histogram (location of peak density)',
    1: 'Mode of 10-bin histogram (finer density peak)',
    2: 'First 1/e crossing of autocorrelation function',
    3: 'First minimum of autocorrelation function',
    4: 'Auto-mutual information of 2-lag time-delay embedding',
    5: 'Time-reversibility statistic (mean of forward-backward diffs)',
    6: 'Proportion of successive RR-interval diffs > 40 ms',
    7: 'Longest stretch of consecutive above-mean values in binary encoding',
    8: 'Transition matrix diagonal sum (3-state coarse-graining)',
    9: 'Periodicity measure via Wang method (threshold=0.01)',
    10: 'Exponential fit residuals in 2-d embedding distance distribution',
    11: 'First minimum of auto-mutual information (40-lag, Gaussian)',
    12: 'Forecast skill ratio: 1-step residual tau / original tau',
    13: 'Outlier inclusion proportion (positive tail, p=0.001)',
    14: 'Outlier inclusion proportion (negative tail, p=0.001)',
    15: 'Welch PSD rectified area in 1/5 band',
    16: 'Longest stretch of consecutive diffs > 0 in binary encoding',
    17: 'Motif-3 quantile entropy from transition histogram',
    18: 'Fluctuation analysis: range-fit scaling exponent (50% overlap)',
    19: 'Fluctuation analysis: DFA scaling exponent (50% overlap)',
    20: 'Welch PSD centroid frequency',
    21: 'Forecast error: 3-step simple mean predictor stderr',
}

CATCH22_SEMANTIC = {
    0: 'Peak density location',
    1: 'Peak density location (finer)',
    2: 'Autocorrelation decay speed',
    3: 'Autocorrelation first-zero lag',
    4: 'Short-range nonlinear dependence',
    5: 'Time irreversibility',
    6: 'Successive variability ratio',
    7: 'Persistence above mean',
    8: 'State transition stability',
    9: 'Periodicity strength',
    10: 'Embedding distance non-periodicity',
    11: 'Long-range mutual information lag',
    12: 'One-step predictability',
    13: 'Positive outlier prevalence',
    14: 'Negative outlier prevalence',
    15: 'Spectral energy concentration',
    16: 'Upward trend persistence',
    17: 'Local pattern diversity',
    18: 'Fluctuation self-similarity (range-fit)',
    19: 'Fluctuation self-similarity (DFA)',
    20: 'Dominant frequency position',
    21: 'Three-step forecast error',
}

CATCH22_INTERPRETATION = {
    0: {'high': 'Distribution concentrated in high-value region',
        'low': 'Distribution concentrated in low-value region'},
    1: {'high': 'Distribution concentrated in high-value region (finer)',
        'low': 'Distribution concentrated in low-value region (finer)'},
    2: {'high': 'Slow autocorrelation decay — distant points still correlated',
        'low': 'Fast autocorrelation decay — series near white noise'},
    3: {'high': 'Long memory — autocorrelation persists over many lags',
        'low': 'Short memory — autocorrelation vanishes quickly'},
    4: {'high': 'Strong nonlinear dependence between adjacent points',
        'low': 'Weak nonlinear dependence between adjacent points'},
    5: {'high': 'Series is time-irreversible (e.g., contains trends or shocks)',
        'low': 'Series is approximately reversible — no clear time direction'},
    6: {'high': 'Frequent successive changes — signal is non-smooth',
        'low': 'Smooth signal with gradual changes'},
    7: {'high': 'Extended runs above the mean (sustained high or low periods)',
        'low': 'Frequent mean-crossing — no sustained deviation'},
    8: {'high': 'Predictable state transitions — tends to stay in same state',
        'low': 'Random state transitions — hard to predict next state'},
    9: {'high': 'Clear periodic repetition pattern in the series',
        'low': 'No periodic structure in the series'},
    10: {'high': 'Embedding distances deviate from exponential (non-typical periodicity)',
         'low': 'Embedding distances follow exponential decay'},
    11: {'high': 'Long-range information dependence (long memory)',
         'low': 'Short-range information dependence only'},
    12: {'high': 'Highly predictable — past values forecast future well',
         'low': 'Hard to predict — near random walk'},
    13: {'high': 'Many extreme positive values (right-skewed or spiky)',
         'low': 'Few extreme positive values'},
    14: {'high': 'Many extreme negative values (left-skewed or deep troughs)',
         'low': 'Few extreme negative values'},
    15: {'high': 'Spectral energy concentrated in a narrow band (dominant frequency)',
         'low': 'Spectral energy spread across frequencies (no dominant tone)'},
    16: {'high': 'Long persistent upward stretches',
         'low': 'Up and down movements alternate frequently'},
    17: {'high': 'High local pattern diversity — complex dynamics',
         'low': 'Repetitive local patterns — simple dynamics'},
    18: {'high': 'Fractal/self-similar fluctuations (multi-scale structure)',
         'low': 'No fractal structure in fluctuations'},
    19: {'high': 'Long-range correlated fluctuations (Hurst > 0.5)',
         'low': 'Uncorrelated fluctuations (near white noise)'},
    20: {'high': 'Dominant frequency in high range (fast oscillation)',
         'low': 'Dominant frequency in low range (slow variation)'},
    21: {'high': 'Large 3-step forecast error — series hard to model',
         'low': 'Small 3-step forecast error — series well captured by linear model'},
}

CATEGORY_FEATURES = {}
for _i, _cat in CATCH22_CATEGORIES.items():
    CATEGORY_FEATURES.setdefault(_cat, []).append(_i)

N_DETECTORS = len(CANDIDATE_MODELS)
N_FEATURES = len(CATCH22_NAMES)
